version: '3.0'

services:
    laravel-vegan-map:
      build: .
      container_name: laravel-vegan-map
      restart: always
      volumes:
        - "./:/app"
      working_dir: /app
      command: "sh ./startup.sh"
      ports:
        - 7008:7008
          #network_mode: host
      networks:
        - local-net

networks:
  local-net:
    external:
      name: local-net
